name: Unity Test Runner

on: [push]

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Unity
        run: |
          UNITY_VERSION=2019.2.11f1
          UNITY_URL="https://download.unity3d.com/download_unity/linux/unity-editor-installer-${UNITY_VERSION}.sh"
          curl -o unity-installer.sh $UNITY_URL
          chmod +x unity-installer.sh
          sudo ./unity-installer.sh --unattended --install-location=/opt/Unity
        
      - name: Run Unity Tests
        run: |
          ./unity-${UNITY_VERSION}/unity-editor/Unity -projectPath ${{ github.workspace }} -runTests -batchmode -returnlicense
